version: '3'

volumes:
  data-base:

services:
  python:
    build: .
    ports:
      - '3000:3000'

    volumes:
      - '.:/google_api_product'

    tty: true
    stdin_open: true

    depends_on:
      - db
    links:
      - db

  db:
    image: mariadb
    volumes:
      - 'data-base:/var/lib/mysql'

    environment:
      # 本番環境では環境変数から参照します。 ex.'MARIADB_ROOT_PASSWORD=${DATABASE_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=mariadb_password'

    ports:
      - '8080:8080'
